#pragma once 

#include <ntddk.h>

#define IOCTL_LIST_PROCESS_NOTIF CTL_CODE(FILE_DEVICE_UNKNOWN, 0x010, METHOD_NEITHER, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_DEREF_PROCESS_NOTIF CTL_CODE(FILE_DEVICE_UNKNOWN, 0x011, METHOD_NEITHER, FILE_READ_DATA | FILE_WRITE_DATA)

#define IOCTL_LIST_THREAD_NOTIF CTL_CODE(FILE_DEVICE_UNKNOWN, 0x020, METHOD_NEITHER, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_DEREF_THREAD_NOTIF CTL_CODE(FILE_DEVICE_UNKNOWN, 0x021, METHOD_NEITHER, FILE_READ_DATA | FILE_WRITE_DATA)

#define IOCTL_LIST_IMAGE_NOTIF CTL_CODE(FILE_DEVICE_UNKNOWN, 0x030, METHOD_NEITHER, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_DEREF_IMAGE_NOTIF CTL_CODE(FILE_DEVICE_UNKNOWN, 0x031, METHOD_NEITHER, FILE_READ_DATA | FILE_WRITE_DATA)

#define IOCTL_LIST_REG_NOTIF CTL_CODE(FILE_DEVICE_UNKNOWN, 0x040, METHOD_NEITHER, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_DEREF_REG_NOTIF CTL_CODE(FILE_DEVICE_UNKNOWN, 0x041, METHOD_NEITHER, FILE_READ_DATA | FILE_WRITE_DATA)


#define IOCTL_PROC_DUP_TOKEN CTL_CODE(FILE_DEVICE_UNKNOWN, 0x051, METHOD_NEITHER, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_PROC_PROTECT CTL_CODE(FILE_DEVICE_UNKNOWN, 0x052, METHOD_NEITHER, FILE_READ_DATA | FILE_WRITE_DATA)

